[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "happy-path"
description = "Code and data flow visualization tool for Python."
authors = [{name = "Timothée Mazzucotelli", email = "dev@pawamoy.fr"}]
license = {text = "ISC"}
readme = "README.md"
requires-python = ">=3.10"
keywords = []
dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Documentation",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = [
    "cappa>=0.19",
    "ujson>=5.9",
]

[project.urls]
Homepage = "https://pawamoy.github.io/happy-path"
Documentation = "https://pawamoy.github.io/happy-path"
Changelog = "https://pawamoy.github.io/happy-path/changelog"
Repository = "https://github.com/pawamoy/happy-path"
Issues = "https://github.com/pawamoy/happy-path/issues"
Discussions = "https://github.com/pawamoy/happy-path/discussions"
Gitter = "https://gitter.im/happy-path/community"
Funding = "https://github.com/sponsors/pawamoy"

[project.scripts]
happy-path = "happy_path.cli:main"

[tool.pdm]
version = {source = "scm"}

[tool.pdm.build]
package-dir = "src"
editable-backend = "editables"
source-includes = ["share"]

[tool.pdm.build.wheel-data]
data = [
    {path = "share/**/*", relative-to = "."},
]
